"""add telegram_chat_id

Revision ID: 0b7a3baf743c
Revises: 884d12143c10
Create Date: 2026-06-06 16:09:26.688768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7a3baf743c'
down_revision: Union[str, None] = '884d12143c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('telegram_chat_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardians', 'telegram_chat_id')
    # ### end Alembic commands ###
