"""initial_schema

Revision ID: 884d12143c10
Revises: None
Create Date: 2026-05-27 00:13:22.369051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884d12143c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_banks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=10), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=200), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('patients',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('rh_factor', sa.String(length=1), nullable=False),
    sa.Column('kell_negative', sa.Boolean(), nullable=False),
    sa.Column('duffy_negative', sa.Boolean(), nullable=False),
    sa.Column('kidd_negative', sa.Boolean(), nullable=False),
    sa.Column('alloimmunization_flag', sa.Boolean(), nullable=False),
    sa.Column('hospital_id', sa.String(length=50), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_transfusion_predicted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hb_current', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_transfusion_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_lower', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_upper', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guardians',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_donation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_eligible_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('donation_count', sa.Integer(), nullable=False),
    sa.Column('response_latency_avg_hours', sa.Float(), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('geography_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'cooldown', 'pending', 'unavailable', 'empty')", name='check_guardian_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('hb_readings',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('hb_value', sa.Float(), nullable=False),
    sa.Column('reading_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_transfusion', sa.Boolean(), nullable=False),
    sa.Column('units_transfused', sa.Integer(), nullable=True),
    sa.Column('hb_rise_per_unit', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('bank_id', sa.String(length=36), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('rh_factor', sa.String(length=1), nullable=False),
    sa.Column('kell', sa.Boolean(), nullable=False),
    sa.Column('duffy', sa.Boolean(), nullable=False),
    sa.Column('kidd', sa.Boolean(), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['blood_banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('hb_readings')
    op.drop_table('guardians')
    op.drop_table('forecasts')
    op.drop_table('alerts')
    op.drop_table('patients')
    op.drop_table('blood_banks')
    # ### end Alembic commands ###
