"""add_six_innovations_models

Revision ID: 930e034a9750
Revises: 884d12143c10
Create Date: 2026-06-06 14:41:06.631206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930e034a9750'
down_revision: Union[str, None] = '884d12143c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_weather_forecasts',
    sa.Column('city_code', sa.String(length=20), nullable=False),
    sa.Column('forecast_week_start', sa.Date(), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=False),
    sa.Column('predicted_demand_units', sa.Integer(), nullable=False),
    sa.Column('current_supply_units', sa.Integer(), nullable=False),
    sa.Column('gap_units', sa.Integer(), nullable=False),
    sa.Column('gap_severity', sa.Enum('surplus', 'balanced', 'shortage', 'critical', name='gapseverity'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('caregiver_checkins',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('raw_response', sa.String(length=1000), nullable=True),
    sa.Column('language_detected', sa.String(length=10), nullable=False),
    sa.Column('symptom_score', sa.Float(), nullable=False),
    sa.Column('fatigue_reported', sa.Boolean(), nullable=False),
    sa.Column('appetite_normal', sa.Boolean(), nullable=False),
    sa.Column('activity_level', sa.Enum('normal', 'reduced', 'very_low', name='activitylevel'), nullable=False),
    sa.Column('caregiver_concern_level', sa.Enum('none', 'mild', 'high', name='concernlevel'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('circle_repair_log',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('departing_guardian_id', sa.String(length=36), nullable=False),
    sa.Column('replacement_guardian_id', sa.String(length=36), nullable=True),
    sa.Column('repair_initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repair_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transition_message_sent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'replacement_found', 'completed', 'failed', name='repairstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departing_guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replacement_guardian_id'], ['guardians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('donor_churn_scores',
    sa.Column('guardian_id', sa.String(length=36), nullable=False),
    sa.Column('cusum_score', sa.Float(), nullable=False),
    sa.Column('engagement_trend', sa.Enum('stable', 'declining', 'critical', name='engagementtrend'), nullable=False),
    sa.Column('predicted_churn_date', sa.Date(), nullable=True),
    sa.Column('reengagement_attempted', sa.Boolean(), nullable=False),
    sa.Column('reengagement_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('donor_engagement_signals',
    sa.Column('guardian_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_latency_hours', sa.Float(), nullable=True),
    sa.Column('response_type', sa.Enum('confirmed', 'declined', 'no_response', name='responsetype'), nullable=False),
    sa.Column('message_channel', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guardian_memorial_messages',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('guardian_id', sa.String(length=36), nullable=False),
    sa.Column('total_donations', sa.Integer(), nullable=False),
    sa.Column('total_days_supported', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transition_consent_given', sa.Boolean(), nullable=False),
    sa.Column('transition_patient_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transition_patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sentinel_alerts',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('triggering_checkin_id', sa.String(length=36), nullable=False),
    sa.Column('hb_at_trigger', sa.Float(), nullable=True),
    sa.Column('predicted_hb_at_trigger', sa.Float(), nullable=True),
    sa.Column('symptom_score_at_trigger', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=False),
    sa.Column('coordinator_notified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_checkin_id'], ['caregiver_checkins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'alerts', ['id'])
    op.create_unique_constraint(None, 'blood_banks', ['id'])
    op.create_unique_constraint(None, 'forecasts', ['id'])
    op.add_column('guardians', sa.Column('telegram_chat_id', sa.String(length=20), nullable=True))
    op.add_column('guardians', sa.Column('annual_donation_count', sa.Integer(), nullable=False))
    op.add_column('guardians', sa.Column('fatigue_ceiling', sa.Integer(), nullable=False))
    op.add_column('guardians', sa.Column('fatigue_rest_until', sa.Date(), nullable=True))
    op.add_column('guardians', sa.Column('fatigue_notified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'guardians', ['id'])
    op.create_unique_constraint(None, 'hb_readings', ['id'])
    op.create_unique_constraint(None, 'inventory', ['id'])
    op.add_column('patients', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'patients', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'status')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'hb_readings', type_='unique')
    op.drop_constraint(None, 'guardians', type_='unique')
    op.drop_column('guardians', 'fatigue_notified')
    op.drop_column('guardians', 'fatigue_rest_until')
    op.drop_column('guardians', 'fatigue_ceiling')
    op.drop_column('guardians', 'annual_donation_count')
    op.drop_column('guardians', 'telegram_chat_id')
    op.drop_constraint(None, 'forecasts', type_='unique')
    op.drop_constraint(None, 'blood_banks', type_='unique')
    op.drop_constraint(None, 'alerts', type_='unique')
    op.drop_table('sentinel_alerts')
    op.drop_table('guardian_memorial_messages')
    op.drop_table('donor_engagement_signals')
    op.drop_table('donor_churn_scores')
    op.drop_table('circle_repair_log')
    op.drop_table('caregiver_checkins')
    op.drop_table('blood_weather_forecasts')
    # ### end Alembic commands ###
